### ISSUE TITLE
Can't display in case of over 50% 

### ISSUE THREAD

**Issue by DarkHorse221** [zilahir/react-donut-chart#1]
Can't display in case of over 50% 
Wanna to let me know solution asap.

**Comment by zilahir** [comment]
@DarkHorse221 i will take a look! thanks for reporting!

**Comment by zilahir** [comment]
@DarkHorse221 i have had an attempt to fix it. 

please give it a try, and let me know. 

`simple-react-donut-chart@0.0.7`

`0.0.7` is the new version

**Comment by zilahir** [comment]
@DarkHorse221 the bug is now fixed. 

https://www.npmjs.com/package/simple-react-donut-chart
